---
# Create Resume
![image](https://github.com/user-attachments/assets/b33a95b0-5b8b-49fa-9285-a48b4f062788)
![image](https://github.com/user-attachments/assets/b0ecad74-dd69-4b63-b709-36351985a60f)
![image](https://github.com/user-attachments/assets/0d2abb0f-2bae-49e3-b6a4-cb92f4007f80)
![image](https://github.com/user-attachments/assets/4719ce43-767b-440e-a1ef-9dcd454598d4)

---
# Merge PDF's
![image](https://github.com/user-attachments/assets/8dc7656f-dfac-4369-b799-78a24f50d2e3)
![image](https://github.com/user-attachments/assets/06ff9ab9-e2f6-4718-adf5-22cb418bdf3b)
![image](https://github.com/user-attachments/assets/771a199b-7207-4cc3-8252-6c66248368bd)

---
### For Resume Maker
![flow_chart](https://github.com/user-attachments/assets/17e043f9-c933-4c50-a623-9f9704b87c13)
![image](https://github.com/user-attachments/assets/401e0a8f-32ae-4732-8e79-b11177806327)
## Accuracy Issue, as you can see the name and other information like connection link's are wrong.
---
## To Work on - <br>
AttributeError: 'response_analysis' object has no attribute 'confidence'
Traceback:
File "D:\LLM\Personal_Utility\ui\app.py", line 49, in <module>
    chack_option()
File "D:\LLM\Personal_Utility\.\ui\sidebar.py", line 86, in chack_option
    call_funct()
File "D:\LLM\Personal_Utility\LLMbackend\llm.py", line 74, in create_resume
    st.session_state.work_flow.invoke(None, config = st.session_state.config)
